### ISSUE TITLE
`setIntervalWait` => `setBlockingInterval`

### ISSUE THREAD

**Issue by JedWatson** [dcousens/react-timers#2]
I was thinking it might be clearer if `setIntervalWait` were named something more obviously related to async terminology, since its use-case is to wait for an async task to complete before resuming the interval.

I think `setBlockingInterval` does a better job of communicating the concept, `setSyncInterval` is another option (since the interval should be sync, not async)

**Comment by dcousens** [comment]
Removed in `3.0.0`.
