### ISSUE TITLE
Auto bind callbacks

### ISSUE THREAD

**Issue by JedWatson** [dcousens/react-timers#3]
Similar to how `React.createClass` autobinds methods

A lot of `var self = this` could be removed from the usage of `react-timers` if callbacks are automatically called in the Component scope.

Seems like syntactic sugar with no downside; you can still pass a bound function or use closures if you like, and I can't think of a single good reason to leave `this` bound to the window.

**Comment by dcousens** [comment]
The use of `var self = this` is still a better practice to save you from constantly rebinding in subsequent scopes.

This is more-like `react`, but I'm not sure if its right to encourage it?
